apiVersion: v1
kind: Pod
metadata:
  name: worker
  labels: 
    app: worker
spec:
  containers:
  - name: worker
    image: dockersamples/examplevotingapp_worker
    # Here we dont need ports coz we are not going to expose this