apiVersion: apps/v1
kind : Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      name: worker
      labels: 
        app: worker
    spec:
      containers:
      - name: worker
        image: dockersamples/examplevotingapp_worker
        # Here we dont need ports coz we are not going to expose this
